---

stages:
  - build
  - deploy

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.8.4
    entrypoint: [""]
  stage: build
  script:
    - make clean setup check build test doc
    - mkdir -p public/
    - cp -r ${CI_PROJECT_DIR}/dist-newstyle/build/x86_64-linux/ghc-8.8.4/sudoku-0.?.?/doc/html/sudoku/* public/
    - make exec
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - dist-newstyle/

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing pages ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
